// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgHboBJCacD5ZU_Y2rQrwjfsyOhEEJDQo',
    appId: '1:330848855288:web:73dd28394da755eb99470d',
    messagingSenderId: '330848855288',
    projectId: 'dochub-6169b',
    authDomain: 'dochub-6169b.firebaseapp.com',
    storageBucket: 'dochub-6169b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr9Jg0y8u_RtCT2ivzhbXpsXIU7o_hmAw',
    appId: '1:330848855288:android:cecc8ce72b614f7199470d',
    messagingSenderId: '330848855288',
    projectId: 'dochub-6169b',
    storageBucket: 'dochub-6169b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-mklXBVk011RZb5kHFTrgh1celDIt3hM',
    appId: '1:330848855288:ios:975127387457523899470d',
    messagingSenderId: '330848855288',
    projectId: 'dochub-6169b',
    storageBucket: 'dochub-6169b.appspot.com',
    iosClientId: '330848855288-bue63tgkh3potm6lvok1uuboj8bfsf4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.dochub',
  );
}
